<script type="text/javascript">
function initLightbox(){
    new Lightbox({
        fadeDuration  : <?php echo (int)Mage::getStoreConfig('tm_easylightbox/general/fadeDuration') ?>,
        resizeDuration: <?php echo (int)Mage::getStoreConfig('tm_easylightbox/general/resizeDuration') ?>,
        wrapAround    : <?php echo (int)Mage::getStoreConfig('tm_easylightbox/general/wrapAround') ?>,
        fitImagesInViewport : <?php echo (int)Mage::getStoreConfig('tm_easylightbox/general/fitImagesInViewport') ?>,
        showImageNumberLabel: <?php echo (int)Mage::getStoreConfig('tm_easylightbox/general/showImageNumberLabel') ?>,
        albumLabel: function(curImageNum, albumSize) {
            return "<?php echo Mage::getStoreConfig('tm_easylightbox/general/labelImage') ?> " + curImageNum + " <?php echo Mage::getStoreConfig('tm_easylightbox/general/labelOf') ?> " + albumSize;
        }
    });
}

//if (Prototype.Browser.IE) {
//    Event.observe(window, 'load', function() { //KB927917 fix
//        initLightbox();
//    });
//} else {
    document.observe("dom:loaded", function() {
        initLightbox();
    });
//}
</script>
