<a href="<?php echo Mage::helper('easylightbox/image')
            ->init($this->imageAttributes['imagepath'])
            ->resize($this->imageAttributes['imagelightboxwidth'],$this->imageAttributes['imagelightboxheight']); ?>"
    rel="lightbox[<?php echo $this->imageAttributes['imagegroup']; ?>]"
    title="<?php echo $this->imageAttributes['imagetitle']; ?>"
    onclick="return false;">
    <img src="<?php echo Mage::helper('easylightbox/image')
                ->init($this->imageAttributes['imagepath'])
                ->resize($this->imageAttributes['imagepagewidth'], $this->imageAttributes['imagepageheight']); ?>"
             alt="<?php echo $this->imageAttributes['imagetitle']; ?>"
    />
</a>